version: '3'

networks:
  laravel:


services:
  app:
    build:
      context: ./dockerfiles
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - "80:80"
    restart: unless-stopped      
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - php
      - db

    networks:
      - laravel

  db:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles/php
      dockerfile: php${PHP_VERSION:-8.2}.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
        - XDEBUG=${XDEBUG:-false}        

    restart: unless-stopped
    volumes:
      - ./src:/var/www/html:delegated
    networks:
      - laravel

  # redis:
  #   image: redis:alpine
  #   restart: unless-stopped
  #   networks:
  #     - laravel
